"""
Supervisor - Routes and coordinates agents
"""
from src.core import get_logger

logger = get_logger("supervisor")

def supervisor_router(state):
    """Router node - just passes state through for routing decision."""
    return state

def route_next(state):
    """Decide which agent to call next (routing logic)."""

    if not state.get("log_analysis"):
        logger.info("→ Routing to: log_analyzer")
        return "log_analyzer"

    if not state.get("root_cause"):
        logger.info("→ Routing to: root_cause_investigator")
        return "root_cause_investigator"

    if not state.get("solution"):
        logger.info("→ Routing to: solution_recommender")
        return "solution_recommender"

    logger.info("→ All agents complete. Compiling report...")
    return "FINISH"

def supervisor_compile(state):
    """Supervisor compiles final incident report."""
    logger.info("📋 Supervisor compiling final report...")

    log_analysis = state.get("log_analysis", "No analysis available")
    root_cause = state.get("root_cause", "No root cause identified")
    solution = state.get("solution", "No solution recommended")

    # Compile professional incident report
    report = f"""
{'='*70}
                    INCIDENT RESPONSE REPORT
{'='*70}

SECTION 1: LOG ANALYSIS
{'-'*70}
{log_analysis}

{'='*70}

SECTION 2: ROOT CAUSE INVESTIGATION
{'-'*70}
{root_cause}

{'='*70}

SECTION 3: SOLUTION RECOMMENDATIONS
{'-'*70}
{solution}

{'='*70}
Report generated by Multi-Agent Incident Response System
Agents: Log Analyzer → Root Cause Investigator → Solution Recommender
{'='*70}
"""

    logger.info("✅ Final report compiled")

    return {
        "incident_report": report,
        "steps_completed": state["steps_completed"] + ["supervisor"]
    }
