"""
TestRail Client - Pushes test cases to TestRail REST API v2
"""
import os
import httpx
from dotenv import load_dotenv

load_dotenv()

PRIORITY_MAP = {
    "critical": 1,
    "high": 2,
    "medium": 3,
    "low": 4
}


class TestRailClient:

    def __init__(self):
        self.base_url = os.getenv("TESTRAIL_BASE_URL", "http://localhost:4002")
        self.email = os.getenv("TESTRAIL_EMAIL")
        self.api_key = os.getenv("TESTRAIL_API_KEY")
        self.auth = (self.email, self.api_key)
        self.headers = {"Content-Type": "application/json"}

    def add_case(self, section_id: int, title: str, steps: list, expected: str, priority: str) -> dict:
        """Push a single test case to TestRail."""
        url = f"{self.base_url}/index.php?/api/v2/add_case/{section_id}"

        payload = {
            "title": title,
            "template_id": 2,
            "custom_preconds": "Generated by AI Agent",
            "custom_steps_separated": [
                {"step": step, "expected": expected} for step in steps
            ],
            "priority_id": PRIORITY_MAP.get(priority.lower(), 3)
        }

        response = httpx.post(url, json=payload, auth=self.auth, headers=self.headers)
        response.raise_for_status()
        return response.json()

    def add_cases_bulk(self, section_id: int, test_cases: list) -> list:
        """Push a list of test cases to TestRail. Returns list of created case IDs."""
        created_ids = []
        for tc in test_cases:
            result = self.add_case(
                section_id=section_id,
                title=tc.get("title", ""),
                steps=tc.get("steps", []),
                expected=tc.get("expected", ""),
                priority=tc.get("priority", "medium")
            )
            created_ids.append(result.get("id"))
        return created_ids
