"""
Supervisor - Routes and coordinates agents
"""
from src.core import get_logger

logger = get_logger("supervisor")


def supervisor_router(state):
    """Passthrough node — LangGraph requires a node to attach conditional edges from."""
    return state


def route_next(state):
    """Decide which agent to call next based on what's missing in state."""

    if not state.get("jira_description"):
        logger.info("→ Routing to: jira_fetcher")
        return "jira_fetcher"

    if not state.get("test_cases"):
        logger.info("→ Routing to: testcase_generator")
        return "testcase_generator"

    if not state.get("testrail_case_ids"):
        logger.info("→ Routing to: testrail_pusher")
        return "testrail_pusher"

    if not state.get("slack_message_ts"):
        logger.info("→ Routing to: slack_notifier")
        return "slack_notifier"

    logger.info("→ All agents complete. Compiling report...")
    return "FINISH"


def supervisor_compile(state):
    """Compile final summary report from all agent results."""
    logger.info("Supervisor compiling final report...")

    jira_key = state.get("jira_key", "N/A")
    jira_summary = state.get("jira_summary", "N/A")
    test_cases = state.get("test_cases", [])
    testrail_ids = state.get("testrail_case_ids", [])
    slack_ts = state.get("slack_message_ts", "N/A")

    report = f"""
{'='*70}
              JIRA → TESTCASE → TESTRAIL → SLACK REPORT
{'='*70}

SECTION 1: JIRA STORY
{'-'*70}
Key     : {jira_key}
Summary : {jira_summary}

{'='*70}

SECTION 2: TEST CASES GENERATED
{'-'*70}
Total   : {len(test_cases)} test cases generated by LLM

{'='*70}

SECTION 3: TESTRAIL PUSH
{'-'*70}
Case IDs: {testrail_ids}

{'='*70}

SECTION 4: SLACK NOTIFICATION
{'-'*70}
Message timestamp: {slack_ts}

{'='*70}
Report generated by Multi-Agent Pipeline
Agents: jira_fetcher → testcase_generator → testrail_pusher → slack_notifier
{'='*70}
"""

    logger.info("✅ Final report compiled")
    return {
        "summary_report": report,
        "steps_completed": state["steps_completed"] + ["supervisor"]
    }
